### ISSUE TITLE
Make more Balance cards to SF/Marin Food Bank

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#256]
either @lippytak or @alanjosephwilliams 

(Cards are better than flyers)

**Comment by alanjosephwilliams** [comment]
That was good to hear from a trusted partner that cards are better than
flyers. We felt that intuitively, but haven't had real data. Qualitative is
a great start.

On Mon, Jan 5, 2015 at 1:22 PM, Dave Guarino <notifications@github.com>
wrote:

> either @lippytak <https://github.com/lippytak> or @alanjosephwilliams
> <https://github.com/alanjosephwilliams>
>
> (Cards are better than flyers)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/balance/issues/256>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
Done.

**Comment by daguar** [comment]
Sweet! :+1: hey @cescacosta, more cards are on the way!

(SEE HOW I JUST INVOKED SOMEONE BY MAGIC THAT WAS AWESOME)
