### ISSUE TITLE
Add solicitation for benefit satisfaction/pain points survey

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#259]

**Comment by lippytak** [comment]
@alanjosephwilliams can you take on ~daily monitoring and sending out gift codes?

**Comment by alanjosephwilliams** [comment]
:thumbsup: no doubt

On Tue, Jan 13, 2015 at 4:43 PM, Jake Solomon <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> can you take
> on ~daily monitoring and sending out gift codes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/balance/issues/259#issuecomment-69850414>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
