### ISSUE TITLE
Turn off outbound text when someone calls

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#263]
This is a quick thing for a bit of a gray area; I checked in with @alanjosephwilliams and he agreed this made sense.

**Comment by alanjosephwilliams** [comment]
:+1: lowest LOE option to align with best-practices in this gray area. In the next sprint we deliberately invest in Balance, perhaps we revisit the more sophistication option that solicits consent (and triggers a text message) with a keypress.

**Comment by daguar** [comment]
Darnit, we need to record new audio files (I realized when testing) because we specify in the current voice file to reply to a text we sent. So #265 is now a prereq for this.
