### ISSUE TITLE
Record new voice audio files for callers

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#265]
For #263, we need new audio files (English and Spanish) for callers. Template text (can be riffed on):

"Hi! You can check your balance over text message by sending a text to this phone number. Or, press 1 to connect to the state telephone system."

@alanjosephwilliams is gonna hit the Food Bank today, so he's going to ask Liliana to record these (I'm assigning you here for that reason Alan.)

Once recorded, @daguar can upload to S3 and change the URLs in the code.

**Comment by alanjosephwilliams** [comment]
New recordings courtesy of Liliana and Francesca now available in dropbox,

**Comment by daguar** [comment]
:+1: Thanks! The quality is good for now, though we may want to rerecord. Call to the demo line to assess for yourself, and open an issue if you think we should: 415-798-2736
