### ISSUE TITLE
Balance 'more info' feature

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#272]
(Edited to spec out by @daguar )

Goal: Ease folks worried about scamming (mostly from AdWords channels)

- [x] Modify MessageGenerator#welcome to say: "Hi there! Reply to this message with your EBT card number and I'll check your balance for you. For more info, text INFO." (English only — see below)
- [x] If a user texts "info" (case-insensitive), then we reply with a basic description of the service. It should contain: the fact that it's a free service (except for standard rates) by Code for America, a non-profit; a URL to a web page with more info.
- [x] Create short URL pointing to CFA Balance app page http://www.codeforamerica.org/apps/balance/

**Comment by daguar** [comment]
Basic spec:

1. Modify `MessageGenerator#welcome` to say: "Hi there! Reply to this message with your EBT card number and I'll check your balance for you. For more info, text INFO." (English + Spanish)

2. If a user texts "info" (case-insensitive), then we reply with a basic description of the service. It should contain: the fact that it's a free service (except for standard rates) by Code for America, a non-profit; a URL to a web page with more info.

**Comment by daguar** [comment]
On second thought, I don't think we need Spanish for this just yet — the core goal here is to assuage users who come through the AdWords (or other low-trust channel) and right now those are only English.

So what we'll do is only modify the English version of `MessageGenerator#welcome` for now.

**Comment by daguar** [comment]
Let's use all caps for INFO for now (after asking @lippytak randomly at midnight what he's seen.)

**Comment by daguar** [comment]
Done with:
- Modify MessageGenerator#welcome to say: "Hi there! Reply to this message with your EBT card number and I'll check your balance for you. For more info, text INFO." (English only — see below)

**Comment by daguar** [comment]
Short URL created — we're reusing c4a.me/balance (was used for instructions during summit) but pointing it to the app page http://www.codeforamerica.org/apps/balance/

**Comment by daguar** [comment]
Turns out "INFO" is a reserved keyword! https://www.twilio.com/help/faq/sms/does-twilio-support-stop-block-and-cancel-aka-sms-filtering 

So we're going to use "ABOUT" instead.

**Comment by daguar** [comment]
Interesting thing I noticed — our previous welcome message said:

> Hi there! Reply to this message with your EBT card number and I'll check your balance for you.

I changed it from "I'll check" to "we'll check" — I think the idea of an individual as opposed to "we" might provide additional feeling of comfort (or at least will feel less weird.)

We could go even further and say "our robots will check" — might be interesting to test this empirically.
