### ISSUE TITLE
Balance response took ~7 mins

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#273]
From our loving user Francesca:
> Hey team,
> I just texted an EBT card # to balance and it responded with the typical “Gracias!” (Which, btw, should have the “¡” preceding it) message, but it took 7 minutes for it to text back. Just thought you guys might want to know.
> Happy Tuesday J

@daguar let's look into this today, though I wouldn't say this requires an immediate fix unless it's happening in all cases. I'll do some manual testing now and report back here.

**Comment by lippytak** [comment]
Eeep, my first try took ~20 mins. I'll bet this has to do with the volume of the start of the month. @daguar let's break and discuss this now.

**Comment by lippytak** [comment]
@daguar is looking into Twilio logs. I am going to:
- try manual call to make sure CA line is working right
- check incoming logs to see how users are reacting

**Comment by lippytak** [comment]
CA line is working as usual.

**Comment by daguar** [comment]
Dev appears to be working with normal latency (one attempt from me).

**Comment by daguar** [comment]
Twilio status board says things are all good: http://status.twilio.com/

**Comment by daguar** [comment]
It doesn't appear that queuing is the issue (Twilio logs say no queue time on responses).

**Comment by lippytak** [comment]
Still seeing intermittent problems, even on a separate subaccount. I texted 8 EBT numbers in quick succession and only got 6 responses:
![screen shot 2015-02-03 at 12 55 20 pm](https://cloud.githubusercontent.com/assets/2533112/6029232/0173fe7e-aba4-11e4-945f-44200d0c2302.png)

Hmmm....

**Comment by lippytak** [comment]
Seems intermittent now and equally affecting all phone numbers, so we're thinking this is a Twilio side issue. Still looking it but consider this officially downgraded from EBF-status.

**Comment by daguar** [comment]
We now have confirmation that there is a Twilio-level issue happening — will report more as we find out.

**Comment by lippytak** [comment]
@daguar I just updated the metrics data as of 2:25pm and glanced through the ~300 balance checks from today. As always there are a few imperfect experience (see below) but I didn't see a single instance of someone complaining about the delay. So I think we're  :+1: and no need to alert users. Feel free to look through yourself and LMK if anything jumps out at you.

![screen shot 2015-02-03 at 2 31 18 pm](https://cloud.githubusercontent.com/assets/2533112/6031109/7bd1038a-abb1-11e4-88b0-c9a9f7e12eb2.png)

**Comment by lippytak** [comment]
BTW the above example is another good case for https://github.com/codeforamerica/balance/issues/272

Also I'm going to message that user personally from our textit.in account right now.

**Comment by lippytak** [comment]
![screen shot 2015-02-03 at 3 12 10 pm](https://cloud.githubusercontent.com/assets/2533112/6031806/39ff19dc-abb7-11e4-8e85-71abd6fa0529.png)

**Comment by lippytak** [comment]
Via our one-of-a-kind Twilio dev evangelist:
>Hey all, 
> Torkel is deploying a fix as we speak. Your transcriptions should be working properly in the very near future. 
> Really appreciate you tracking this one down for us. I think y'all are are hooked up on credits through Twilio.org, but if you need more dropped in your account in the future, or if y'all need some Twilio t-shirts, let me know.

Just tested with 10 simultaneous balance checks and got back LIGHTNING FAST (~60 seconds) responses:
![screen shot 2015-02-04 at 10 45 58 am](https://cloud.githubusercontent.com/assets/2533112/6046937/3cef1f44-ac5b-11e4-8f75-2afa62155584.png)

Looks like this issue is :+1:

**Comment by lippytak** [comment]
(oops wrong screenshot...edited!)
