### ISSUE TITLE
Compensate (or confirm already done) lingering survey respondents

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#274]
I noticed that a couple lingering people responded to the survey after we turned off solicitations:
![textitin](https://cloud.githubusercontent.com/assets/2533112/6031813/510a8706-abb7-11e4-9bec-d79523d2cbcf.png)

Let's make sure everyone has gotten compensated. Also for future ref make sure to set uncaught messages back to the global-router flow so we get emailed when unanticipated messages come through:
![screen shot 2015-02-03 at 3 12 46 pm](https://cloud.githubusercontent.com/assets/2533112/6031896/f7230820-abb7-11e4-82d7-bbe5707e3bcd.png)

This should be a quickie so I'm dropping it into this week. Hope that's cool!

**Comment by alanjosephwilliams** [comment]
Good catch. I've responded and sent a second gift code along as a way to
say thanks for his or her patience. I'll close this issue when I can
confirm no other post-close survey takers are waiting.

On Tue, Feb 3, 2015 at 3:19 PM, Jake Solomon <notifications@github.com>
wrote:

> Assigned #274 <https://github.com/codeforamerica/balance/issues/274> to
> @alanjosephwilliams <https://github.com/alanjosephwilliams>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/balance/issues/274#event-229662971>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
