### ISSUE TITLE
Ask Jim to write a thing about Balance risk assessment

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#277]
Jim couldn't make any promises but was down to help. If we send him a formal request (brief background + the ask) then he'll review it with his team and suggest the best path forward. Note if we phrase it as a 'question of legal interpretation' then they're obligated to respond, but this probably isn't the right path as we want more of an assessment of risk.

@RebeccaCoelius assigning to you and I'll slack you his contact info. Ping me with questions.

**Comment by RebeccaCoelius** [comment]
@lippytak did he suggest any other words that will allow them to share their opinion without making them legally culpable? for example, "share your thought process when you approved the usage of Balance in the state of CA".

**Comment by lippytak** [comment]
@RebeccaCoelius no, but definitely ask this in your note.

Also note that they didn't 'approve' Balance but rather offered an assessment of the risk (low).

**Comment by lippytak** [comment]
Cleaaaaanup! Feel free to re-open if it's still relevant.
