### ISSUE TITLE
Setup monitoring for when transcription callbacks break

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#287]
This has happened twice so far (we think): https://github.com/codeforamerica/balance/issues/286

Not knowing is not good.

**Comment by daguar** [comment]
After consulting with some folks (thanks @migurski @tmaybe and dev meetup!) here's what I'm thinking the best approach is:

1. Every ~15 minutes, find the most recent "Thanks! Please wait..." message (via Twilio API) that happened >5 minutes ago
2. Using the user's phone # in that message, look for a more recent outbound message to that user with some sort Balance response (any of the possible ones)

An additional level of coverage would be using Alan's EBT # to issue a balance check every N minutes, which would be as close to a "full smoke test" that we could get (ie, it checks our server, Twilio, the state phone line — pretty much everything.)

**Comment by daguar** [comment]
in progress
