### ISSUE TITLE
Send 1000 Balance cards to Marin

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#307]
Balance #: (415) 319-6624

Send to:
> Attn: Martin J. Graff
Department of Health and Human Services
120 N. Redwood Drive
P.O. Box 4160
San Rafael, CA 94913-4160

**Comment by lippytak** [comment]
@alanjosephwilliams could you get these out this week?

**Comment by daguar** [comment]
If we are not super keen on promoting ebtnearme (I'm not) can I suggest we set up a Spanish # and make front/back Balance Spanish/English?

**Comment by daguar** [comment]
Also caseload is like 3k so maybe 500 for now?

**Comment by alanjosephwilliams** [comment]
Front English, Back Spanish
1000 cards.
![balance-english-spansih_back](https://cloud.githubusercontent.com/assets/2983464/7659044/0a85e316-faf4-11e4-8dfd-b188055405f6.jpg)
![balance-english-spansih_front](https://cloud.githubusercontent.com/assets/2983464/7659045/0a871984-faf4-11e4-81e7-ab11710e6a65.jpg)

**Comment by alanjosephwilliams** [comment]
that awful green is just the CMYK (color scheme used for print good)s being converted into web colors by github.

**Comment by daguar** [comment]
:+1:

**Comment by lippytak** [comment]
@alanjosephwilliams let's make this happen with the best address we have

**Comment by alanjosephwilliams** [comment]
@lippytak what address is that? We need a non-PO box.

**Comment by lippytak** [comment]
>Attn: Martin J. Graff
Department of Health and Human Services
20 N San Pedro Rd
San Rafael, CA 94903

**Comment by alanjosephwilliams** [comment]
thank you @lippytak!

**Comment by daguar** [comment]
Did these go out already? Wasn't sure but doing waffle cleanup so please close if so.

**Comment by alanjosephwilliams** [comment]
Yes, but let's close when we confirm they have been received.

On Fri, Jun 5, 2015 at 12:06 PM, Dave Guarino <notifications@github.com>
wrote:

> Did these go out already? Wasn't sure but doing waffle cleanup so please
> close if so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/balance/issues/307#issuecomment-109400567>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
