### ISSUE TITLE
IVR system is sometimes ignoring digits pressed

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#324]
New issue: sometimes hearing a message that there weren't enough digits pressed. (It's wrong because we see in the Twilio log that they were programmatically pressed, but it's not recognizing them.)

**Comment by daguar** [comment]
Weirdly, the frequency of this error has plummeted — it's maybe happening ~5% of the time.

It may have been an upstream problem with the IVR system (or with Twilio) or it may have been our fix.

Regardless, cool! Closing this.

**Comment by lippytak** [comment]
BEN FIXED IT!

**Comment by daguar** [comment]
Well, okay, that's _one_ interpretation.
