### ISSUE TITLE
Alert: Elevated HTTP retrieval failure errors in production

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#327]
More details to come

**Comment by daguar** [comment]
Incident postmortem: it appears that Twilio cleared a backlog of delayed transcriptions that must have been _very_ old (at least 2 months) because they were sent to a URL structure that we haven't had in that long.

These showed up as 404s because of the new URL structure.

Blech.

**Comment by lippytak** [comment]
LOL
