### ISSUE TITLE
Balance link broken in ABOUT text

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#328]
www.c4a.me/balance should be http://c4a.me/balance

**Comment by daguar** [comment]
Well that's no good! Do you know, was this part of the transition to the bitly replacement? If so I'll want to ping David to add support for www anyway since I'm guessing we're not the only ones affected.

**Comment by lippytak** [comment]
I pinged him, not sure yet

On Tue, Nov 3, 2015 at 8:40 AM, Dave Guarino < notifications@github.com > wrote:
Well that's no good! Do you know, was this part of the transition to the bitly
replacement? If so I'll want to ping David to add support for www anyway since
I'm guessing we're not the only ones affected.
