### ISSUE TITLE
Issues reported by Francesca

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#330]
Sounds like @lippytak partially verified — sounds like we're getting a high level of "sorry!" for California calls.

**Comment by lippytak** [comment]
Alrighty, believe I figured this out. Closing and will open another issue with details. Heads up @daguar and @alanjosephwilliams Balance is essentially down for most CA users right now.

**Comment by daguar** [comment]
:(

**Comment by lippytak** [comment]
See #332 for details
