### ISSUE TITLE
Fix CA regex

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/balance#332]
So right now every CA user who DOES NOT have a positive SNAP AND Cash balance is getting the `having_trouble_try_again_message` response:
![screen shot 2015-12-17 at 12 06 02 pm](https://cloud.githubusercontent.com/assets/2533112/11880613/9fc37e68-a4b6-11e5-8aa9-199e96442f39.png)

Here are our 50 most recent outbound texts on our main CA number:
![screen shot 2015-12-17 at 12 03 35 pm](https://cloud.githubusercontent.com/assets/2533112/11880698/2d3df868-a4b7-11e5-940a-47e9d8272c77.png)

The reason is that Twilio (or the provider) changed their transcription content to return 'zero dollars' instead of '$0.00' and our regex isn't catching these. Because in CA we're always looking for 2 matches (`elsif regex_matches.count > 1`), then if either balance transcription returns 'zero dollars'  we just return `having_trouble_try_again_message`.

Example new transcription:
> Balance is $243.28. Your cash account balance is zero dollars.
https://www.twilio.com/user/account/voice/log/transcriptions/TR318ef554ff99dcbe8b7191504685803c

SO, I think if we just start picking up 'zero dollars' in our CA handler regex then we should be all good.

**Comment by daguar** [comment]
:+1: Moving to current sprint

**Comment by lippytak** [comment]
Two additional things:
- Since the issue is with the underlying Twilio transcription this is probably affecting all states, so we should update all handlers.
- Looks like this has been happening since late October, so we should brainstorm how to setup monitoring that catches similar cases in the future.

**Comment by daguar** [comment]
:sob:

**Comment by daguar** [comment]
Closed by #333 — adding this to other states is #334 and expanding this to values beyond zero is #335
