### ISSUE TITLE
Alaska has new message right after the balance info that breaks AK Balance

### ISSUE THREAD

**Issue by brendanbabb** [codeforamerica/balance#342]
Alaska just introduced MyAlerts a way to get a text or e-mail when a deposit is made to a food stamp account. This is cool, but breaks the transcription of the balance amount. I am not sure how it works with the Twilio transcription issue.

**Comment by daguar** [comment]
How do you know it breaks it?

**Comment by brendanbabb** [comment]
Good point if the Twilio issue was intermittent. I noticed the problem on 12/31 and tested California Bakance at the same time and it was working. I should double check.

**Comment by brendanbabb** [comment]
Pretty sure it is the Twilio number transcription issue. Closing the issue.

**Comment by daguar** [comment]
:+1:
