### ISSUE TITLE
Make transcription parser capable of handling English-language dollar amounts like "forty two dollars"

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#343]
TLDR: The Balance service is broken right now because of an unannounced change in Twilio's transcription API; this issue details that and lays out a potential approach to fix, asking for help to do so

### Overview

The Balance service stopped working for users at some time on 12/30 when Twilio changed the service provider they use for transcribing audio ( issue #337 )

What happened is that the transcription API used to transcribe dollar amounts in the format $12.43 but the new service transcribes audio saying dollar amounts as straight English language words. Example:
- Before: "... your food stamp balance is $42.45 ..."
- Now: "... your food stamp balance is forty two dollars and forty five cents ..."

The current code base relies on simple regex's looking for stuff like "$24.43" ([see one example of the balance amount parsing code here](https://github.com/codeforamerica/balance/blob/master/lib/state_handler/ca.rb#L16-L21) ) and so this change has broken the current code's ability to get balance amounts out of the transcribed audio of the IVR system reading out the balance.

I've contacted Twilio, they're sorry this happened and are looking into getting the new provider to transcribe dollar amounts consistently with the old approach, but that probably won't happen in the near term.

I've also put up an outage message ("check back in a few days" more or less, #339 ) for all current users so as to properly set expectations.

### A potential fix (help wanted!)

This can probably be fixed if we can preprocess transcriptions and consistently transform English-language dollar amounts like _forty two dollars and eighty cents_ into "$42.80", and then we can just lean on the old naive parser to yank out those amounts.

It looks like there's [a Ruby gem called numbers_in_words](https://github.com/markburns/numbers_in_words) that can take numbers as English words and transform them to numbers, for example:

```ruby
NumbersInWords.in_numbers("nineteen sixty five") # => 1965
```

Unfortunately at first glance it doesn't look like it can take a huge chunk of text and convert just the numbers, so we'd need to "locate" the number strings, but it's promising.

I can't allocate significant effort to this right now, so I'm turning on the bat signal with this issue to see if anyone is interested in giving this a shot. Help some of the most vulnerable and underserved folks in the US and do it by solving a programming puzzle!

cc @tmaybe @ondrae @brendanbabb @bigfleet @jdungan @stanzheng @GregBaugues 

### Test data to implement code against

- Your food stamp balance is six dollars and twenty five cents.  Your cash account balance is eleven dollars and sixty nine cents.  As a reminder.  By saving the receipt from your last purchase and or your last cash purchase or cashback Prinz action.  You will always have your. 

- Your snap balance is four hundred twenty six dollars.  Your cash balance is zero dollars.  As a reminder by saving the receipt from your last purchase you will know your current balance.  Remember you can also access your account information online at. 

- One moment please.  OK.  I've pulled up your account information.  Your food stamp balance is seven hundred sixty six dollars and thirty seven cents.  You are eligible to enroll in a free service called my own. 

- One moment please.  OK.  I've pulled up your account information.  Your food stamp balance is seven hundred sixty six dollars and thirty seven cents.  You are eligible to enroll in a free service called my alerts. 

- Balance is one hundred seventy one dollars and sixty eight cents.  Your cash account balance is zero dollars and ninety cents.  As a reminder.  By saving the receipt from your last purchase and or your last cash purchase or cashback transaction.  You will always have you. 

- Balance is four hundred one dollars and twenty three cents.  Your cash account balance is two dollars and fifty one cents.  As a reminder.  By saving the receipt from your last purchase and or your last cash purchase or cashback transaction.  You will always have your current. 

- Snap balance is three hundred fourteen dollars.  Your cash balance is zero dollars.  As a reminder by saving the receipt from your last purchase you'll know your current balance.  Remember you can also access your account information online at W W. 

#### One other weird edge case: "zero" == "the euro"

The change introduced another weird case — it's now sometimes transcribing zero as "the euro", for example:

- Balance is the euro.  Dollars.  Your cash account balance is five hundred forty one dollars as a reminder.  By saving the receipt from your last purchase and or your last cash purchase or cashback transaction.  You will always have your current balance.  Some A.T.M.'s will also print your balance on a cash with the. 

So a bonus would be code that processes the above so into "Balance is $0. Your cash account balance is $541..."

**Comment by BrainScraps** [comment]
I'm going to give this a go tonight. I'll keep you all posted.

**Comment by stevenbuccini** [comment]
Hey @daguar,

This sounds like something that is a good fit for my skills and abilities. I'd be happy to whip up a fix if it hasn't been claimed already.

The good news is that the gem you found filters out extraneous words. 
```rb
2.2.0 :009 > NumbersInWords.in_numbers("Balance is one hundred seventy one dollars")
=> 171
```

The bad news is that if there are multiple numbers in a string, it appears that gem adds them together:
```rb
2.2.0 :008 > NumbersInWords.in_numbers("Balance is one hundred seventy one dollars and sixty eight cents.") 
=> 239
```


My proposal is to split `processed_text` on periods, then scan each sentence for "dollars" or "cents". A sentence our "candidate sentences" which require further processing. If both "dollars" and "cents" are present, we split the candidate sentence in half on "dollars" and process each half using the gem. Else, we can feed the sentence into the gem as is.

Once we get the number(s) back from the gem, we can use simple string formatting to stitch them into the required format.

If this plan seems fine, I'll go ahead and get started!

**Comment by daguar** [comment]
@brainscraps @stevenbuccini Awesome thanks!

Steven - I think an issue with your approach is that it may not work with cents amounts (it sounds like it will add the cents number to the dollar amount) so it may be necessary to do some splitting on dollars and cents (keeping in mind cents is indeed optional.) I also think that the phrase "cash balance" may be more consistent than the period in general (though I'll try to pull some more test data to confirm)

**Comment by daguar** [comment]
OH sorry! I read too quickly on the train! I think that approach makes sense.

**Comment by etrepum** [comment]
Here's a quick hack: https://gist.github.com/etrepum/914da530c69e01340ecd

**Comment by BrainScraps** [comment]
@etrepum that's pretty excellent - do you mind if I put the guts of your fix into the specs of the app itself?

**Comment by niklas** [comment]
@etrepum 's solution might be faster, but mine also accepts numbers outside of "balance is". YMMV

do what you want with it ;-)

**Comment by etrepum** [comment]
@BrainScraps feel free to use it any way you want (happy to assign copyright or whatever if that's the process here). #344 looks like it may be more robust though, if any amounts fall outside of the "balance is …" pattern.

**Comment by daguar** [comment]
This activity makes me so, so happy — thank you! In terms of weighing different options, I can also pull a larger sample from production data and check to see if there are any edge cases not caught in what I've posted here.

**Comment by BrainScraps** [comment]
since @niklas has such a solid PR, I'm going to suspend further efforts unless something goes off the rails. thanks all!

**Comment by daguar** [comment]
@niklas's PR is most excellent! (THANK YOU AGAIN!) I'm cross-posting from the PR the 2 additional edge cases I found running data through it in case anyone else would like to stab at modifying that PR code to handle these new cases:

I ran this through a broader sample to do some QA and found 2 additional edge cases not covered in the sample transcriptions I gave:

1. It looks like single-digit cents amounts don't transcribe correctly right now

Example:

"Balance is twenty two dollars and eight cents.  Your cash account balance is zero dollars and sixty eight cents.  As a reminder..."

transcribes to

""Balance is **$22.80.**  Your cash account balance is $0.68.  As a reminder..."

2. A SUPER SECRET DOUBLE-BONUS weird one of zero being transcribed to "the row"

Example:

"One moment please.  OK.  I've pulled up your account information.  Your food stamp balance is the row.  Dollars and forty two cents.  You are"

If these are easy/interesting for you to try and cover @niklas that'd be great, otherwise I or someone else will try to modify for that.

Thanks so much again! I'm hoping to get the service back up today or tomorrow since this fix takes us ~95% of the way.

**Comment by etrepum** [comment]
I went ahead and simplified #344 to make it support these edge cases, new PR in #345 (mostly still @niklas' work)

**Comment by daguar** [comment]
Balance is now BACK UP AND OPERATIONAL! Woo-hoo!

Thanks to everyone who helped out and got such awesome code shipped so quickly. Thanks to you, a lot of folks are going to have a much easier time checking their EBT balance.

**Comment by daguar** [comment]
I've found 2 more funky edge cases (sort of a given when we're creating a psuedo-API from calling, recording, and transcribing a telephone IVR system) and have added a branch with failing tests if anyone here is interested in helping with those:
https://github.com/codeforamerica/balance/issues/348

**Comment by daguar** [comment]
Hey everyone — Twilio's is changing their transcription service effective tomorrow 1/27 with a different approach to numbers: they will now transcribe _numbers_, but they will not pre-process them into dollar amounts.

Example new transcription result (from a real recording):
- "Balance is 1 4 8 dollars and 9 2 cents. Your cash account balance is the euro. Dollars as a reminder. By saving the receipt from your last purchase and or your lastcash purchase or cashback transaction. You will always have your current balance. Some A.T.O.."

I've opened a new issue ( #351 ) for this.

This change is going live tomorrow — I am going to try and work on a fix, but otherwise will probably have to turn off the service tomorrow until I have more time to ship one.

If someone here has time to do a quick modification of the awesome DollarAmountsProcessor that solved this bug, your time would help a lot of people out (me too, but I'm the least important person helped out here.)

**Comment by etrepum** [comment]
#352 works for those samples
