### ISSUE TITLE
Add support for new Twilio number transcriptions coming 1/27

### ISSUE THREAD

**Issue by daguar** [codeforamerica/balance#351]
Supposedly a _new_ change is coming in Twilio's transcriptions API tomorrow (1/27) that will start transcribing audio saying numbers into numbers, for example "56". I've asked for some of our existing recordings to be run through their new version so we can anticipate the exactly what will come out and write a fix proactively sometime today.

**Comment by daguar** [comment]
They've got sample audio from us and sounds like they'll turn around some test data today

**Comment by daguar** [comment]
Okay, here are some sample transcriptions for the new system (based on actual recordings):

- "Balance is 1 4 8 dollars and 9 2 cents. Your cash account balance is the euro. Dollars as a reminder. By saving the receipt from your last purchase and or your lastcash purchase or cashback transaction. You will always have your current balance. Some A.T.O.."
 - Actual amounts: $148.92 and $0.00

- "Step balance. Is 2 7 1 dollars and 8 7 cents. Your cash account balance. Is the euro. Dollars. As a reminder. By saving the receipt from your last purchase. And oryour last. Cash purchase or cashback transaction. You will always have your current balance."
 - Actual amounts: $271.87 and $0.00

- "moment please. OK. I've pulled up your account information. Your food stamp balance is 0 dollars and 2 0 cents. You are eligible to enroll in a free service called myalerts. With my."
 - Actual amount: $0.20

- "Balance is 2 6 dollars. And boy 6 cents. Your cash account balance is 0 dollars as a reminder. By saving the receipt from your last purchase and or your last cashpurchase or cashback transaction. You will always have your current balance. Some A.T.M.'s will also."
 - Actual amounts: $26.46 and $0.00
 - This one is an edge case, and I'm not going to block shipping a fix on it (but it'd be bonus to get)

This change is going live tomorrow — I am going to try and work on a fix, but otherwise will probably have to turn off the service tomorrow until I have time to ship one. If someone has time to do a quick modification, your time would help a lot of people out.

**Comment by alanjosephwilliams** [comment]
nudge for an update @daguar

**Comment by daguar** [comment]
Closed by #352
